service: team-2

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  stage: dev
  region: eu-west-1

package:
  individually: true

functions:
  scrapy:
    runtime: python3.8
    handler: job_scrape.lambda_handler
    timeout: 500
    module: lambda
    include:
      - lambda
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
        Resource:
          - arn:aws:s3:::linkedinwebscrap
          - arn:aws:s3:::linkedinwebscrap/*
  graphing:
    runtime: python3.8
    handler: matplotlib_test.lambda_handler
    timeout: 500
    module: graph_lambda
    include:
      - graph_lambda
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
        Resource:
          - arn:aws:s3:::linkedinwebscrap
          - arn:aws:s3:::linkedinwebscrap/*